### PR TITLE
ios_vlans private vlans support

### PR DESCRIPTION
**Pull request by UvixCreative**
##### SUMMARY

Add support for private vlans configuration to ios_vlans. Fixes ansible-collections/cisco.ios#693

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

`ios_vlans`

##### ADDITIONAL INFORMATION
This is my first contribution to Ansible. I've written and tested my changes successfully, but these are items I'm still uncertain about at time of writing:
- I was not able to figure out how to run integration tests. I wrote 1 integration test, but was not able to write a more complete test because I couldn't figure out how to run it myself
- I'm not certain if the unit tests I wrote are thorough enough, feedback would be appreciated

### CODE REVIEW

**Comment by bentole** [comment]
Hi @UvixCreative! Nice work on the module! Don't know why you were not able to run the integration tests, but the command itself is, by using the route maps module as an example: `ansible-test network-integration --inventory /tmp/hosts.ini ios_route_maps` after first creating a temporary hosts file in `/tmp/`.  Hope this helps you a bit further.

**Comment by KB-perByte** [comment]
@UvixCreative The UTs added look fine to me.
Where you able to run the integration tests for ios_vlans?

**Comment by UvixCreative** [comment]
bentole's comment was very helpful, I just haven't gotten around to running the integration tests. I take it that's something I should do on my own before your review?

If so, is there anything special I need to set up on the device beforehand, or will it set up everything when it runs?

**Comment by KB-perByte** [comment]
@UvixCreative you need not do anything beforehand 
`ansible-test network-integration --python 3.10 --inventory /..//inventory ios_vlans -vvvv` it would just run the concerned vlan specific test. Once that passes things are done!
Regards.

**Comment by KB-perByte** [comment]
@UvixCreative are we good to merge this do you want to add anything to the PR?

**Comment by UvixCreative** [comment]
@KB-perByte Unless there are any problems that you know of, I'm done with it, should be good to merge. Thank you!

**Pull request merged**
