### PR TITLE
Fixes multiple ios_user bugs

### PR DESCRIPTION
**Pull request by roverflow**
##### SUMMARY
Fixed a bug which did not set type 7 password and type 9 secret correctly.
Fixed an issue where the ssh users were not being removed correctly on purge.

fixes issue - #950 #949

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
 `ios_user.py`

### CODE REVIEW

**Review by KB-perByte — APPROVED** [review]

**Comment by rowco** [comment]
This commit has re-introduced the issue that was resolved by #889. The regex in the terminal plugin ios.py is far too wide. In my case 'show run' is failing because we have the string 'Error:' in the config.

**Comment by KB-perByte** [comment]
Cc @roverflow

**Comment by roverflow** [comment]
> Cc @roverflow 

Will take a look!

**Comment by rowco** [comment]
> > Cc @roverflow
> 
> Will take a look!

@roverflow  - any update on this?

**Pull request merged**
