### PR TITLE
ios_vlans - add error regex for vlan name longer than 32 characters

### PR DESCRIPTION
**Pull request by KB-perByte**
##### SUMMARY

ios_vlans - Make the module fail when vlan name is longer than 32 characters with configurations as VTPv1 and VTPv2.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_vlans

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jorgenspange** [comment]
Tried this now, and this is the result when running towards Cisco Catalyst 9600:

```yaml
 _______________________________________________________________________________
 TASK [Make VLAN config changes, expect it should fail as vlan name is more than 32 chars]
 --------------------------------------------------------------------------------------------
changed: [Catalyst9600] => changed=true
  after:
  - mtu: 1500
    name: default
    shutdown: disabled
    state: active
    vlan_id: 1
  - mtu: 1500
    name: Ansible_Test_Description_Modified
    shutdown: disabled
    state: active
    vlan_id: 5
  commands:
  - vlan 5
  - name Ansible_Test_Description_Modified
  - state active
```

Did not fail.

tried towards Catalyst 9300 aswell, and even added some more characters, but still not failing:

```yaml
 __________________________________________________________
/ TASK [Make VLAN config changes, expect it should fail as \
\ vlan name is more than 32 chars]                         /
 ----------------------------------------------------------
       \   ,__,
        \  (oo)____
           (__)    )\
              ||--|| *

changed: [Catalyst9300] => changed=true
  after:
  - mtu: 1500
    name: default
    shutdown: disabled
    state: active
    vlan_id: 1
  - mtu: 1500
    name: Ansible_Test_Description_Modified_Extra_Characters
    shutdown: disabled
    state: active
    vlan_id: 5
  commands:
  - vlan 5
  - name Ansible_Test_Description_Modified_Extra_Characters
  - state active
```

**Comment by KB-perByte** [comment]
Closing this off in favor of this https://github.com/ansible-collections/cisco.ios/pull/1069

Regards

**Comment by KB-perByte** [comment]
@jorgenspange can you check, if you are getting the error while you do the configuration via the appliance's cli?
Regards. Thanks for your help!

**Comment by roverflow** [comment]
image
image

@KB-perByte getting the correct error

**Review by roverflow — APPROVED** [review]

**Comment by KB-perByte** [comment]
We can merge and release it then

**Pull request merged**
