### PR TITLE
[DNM] Test 2.12 testing

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/1143
Depends-on: https://github.com/ansible-collections/cisco.ios/pull/436

##### ISSUE TYPE

- Test Pull Request

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by GomathiselviS** [comment]
@Qalthos  For the integration test jobs to run, the files under the plugins folder should be modified ( for git diff ).

**Comment by Qalthos** [comment]
recheck

**Comment by KB-perByte** [comment]
recheck

**Pull request closed without merging**
