### PR TITLE
To fix ios_acls Nonetype error when aces are empty

### LINKED ISSUE #257: Running ios_acls module with action states results in "'NoneType' object is not iterable" error.
##### SUMMARY

Although I'm not providing an empty object, I get the following error with all of merged, replaced and overridden states:
```
(env) [vagrant@server1 ansible]$ ansible-playbook update_acls.yml -v
Using /home/vagrant/ansible/ansible.cfg as config file

PLAY [ios1] ********************************************************************************

TASK [parse configuration] *****************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [ios1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/vagrant/.ansible/tmp/ansible-local-3450k77oq2fg/ansible-tmp-1614248538.182234-3455-195309495905390/AnsiballZ_ios_acls.py", line 102, in <module>
        _ansiballz_main()
      File "/home/vagrant/.ansible/tmp/ansible-local-3450k77oq2fg/ansible-tmp-1614248538.182234-3455-195309495905390/AnsiballZ_ios_acls.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/vagrant/.ansible/tmp/ansible-local-3450k77oq2fg/ansible-tmp-1614248538.182234-3455-195309495905390/AnsiballZ_ios_acls.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1415, in <module>
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in main
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 43, in __init__
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/resource_module.py", line 46, in __init__
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/resource_module.py", line 64, in gather_current
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/resource_module.py", line 110, in get_facts
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 121, in get_facts
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 85, in populate_facts
    TypeError: 'NoneType' object is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *********************************************************************************
ios1                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_acls module
##### ANSIBLE VERSION

```paste below
(env) [vagrant@server1 ansible]$ ansible --version
ansible 2.10.6
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/env/lib/python3.8/site-packages/ansible
  executable location = /home/vagrant/env/bin/ansible
  python version = 3.8.7 (default, Feb 19 2021, 15:35:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### CONFIGURATION

```paste below
(env) [vagrant@server1 ansible]$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/vagrant/ansible/ansible.cfg) = ['/home/vagrant/ansible/hosts']
DEFAULT_STDOUT_CALLBACK(/home/vagrant/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/vagrant/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/vagrant/ansible/ansible.cfg) = /home/vagrant/env/bin/python3.8
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/vagrant/ansible/ansible.cfg) = 500
```

##### OS / ENVIRONMENT

Centos 7 ansible controller, Network platform: Cisco IOS XE Software, Version 16.06.04, cisco.ios collections 1.3.0

##### STEPS TO REPRODUCE

(env) [vagrant@server1 ansible]$ more update_acls.yml 
```
---
- hosts: ios1
  gather_facts: no
  collections:
  - cisco.ios
  tasks:
  - name: parse configuration
    ios_acls:
      config:
      -   acls:
          -   aces:
              -   destination:
                      address: 20.2.2.0
                      port_protocol:
                          eq: www
                      wildcard_bits: 0.0.0.255
                  grant: permit
                  protocol: tcp
                  sequence: 10
                  source:
                      address: 10.2.2.0
                      wildcard_bits: 0.0.0.255
              -   destination:
                      any: true
                      port_protocol:
                          eq: www
                  grant: permit
                  protocol: tcp
                  sequence: 20
                  source:
                      any: true
              acl_type: extended
              name: '101'
          afi: ipv4
      state: merged
```
```
(env) [vagrant@server1 ansible]$ ansible-playbook update_acls.yml -v
Using /home/vagrant/ansible/ansible.cfg as config file

PLAY [ios1] ********************************************************************************

TASK [parse configuration] *****************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [ios1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/vagrant/.ansible/tmp/ansible-local-3450k77oq2fg/ansible-tmp-1614248538.182234-3455-195309495905390/AnsiballZ_ios_acls.py", line 102, in <module>
        _ansiballz_main()
      File "/home/vagrant/.ansible/tmp/ansible-local-3450k77oq2fg/ansible-tmp-1614248538.182234-3455-195309495905390/AnsiballZ_ios_acls.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/vagrant/.ansible/tmp/ansible-local-3450k77oq2fg/ansible-tmp-1614248538.182234-3455-195309495905390/AnsiballZ_ios_acls.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1415, in <module>
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in main
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 43, in __init__
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/resource_module.py", line 46, in __init__
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/resource_module.py", line 64, in gather_current
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/resource_module.py", line 110, in get_facts
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 121, in get_facts
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_ios_acls_payload_v5dspav2/ansible_ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 85, in populate_facts
    TypeError: 'NoneType' object is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *********************************************************************************
ios1                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

```yaml

```

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by justjais**
##### SUMMARY

To fix ios_acls Nonetype error when aces are empty. Fixes #257

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_acls

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Review by NilashishC — APPROVED** [review]

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Pull request merged**
