### PR TITLE
Re-work stderr regex to ensure presence of %

### PR DESCRIPTION
**Pull request by rowco**
##### SUMMARY

Fix to #889, regex was to wide and was picking up a string with "xxx Error:" and failing. Fix is to ensure the presence of the % anchor.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

terminal

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rowco** [comment]
@KB-perByte - as discussed.

**Comment by KB-perByte** [comment]
You would need to add a changelog to the PR.
We can skip adding test to this.

I would stall the PR for sometime to check any impact of this thoroughly.
Regards

**Comment by KB-perByte** [comment]
@rowco I think we can merge this PR, would you please add a changelog to the PR.
Regards.

**Comment by rowco** [comment]
Hi @KB-perByte - added the changelog. Hope it ok.

**Pull request merged**
