### PR TITLE
Added support for interface Tunnel

### PR DESCRIPTION
**Pull request by benjdudas**
##### SUMMARY

Fixes: https://github.com/ansible-collections/cisco.ios/issues/144

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by justjais** [comment]
@benjdudas Thanks for raising the PR for fixing the issue, changes LGTM can you please add changelog for the PR for the tests to pass.

**Comment by benjdudas** [comment]
@justjais changelog added

**Review by justjais — APPROVED** [review]

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
@benjdudas can u [rebase](https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html) the fix and update the PR as that's stopping the PR from getting merged.

**Comment by benjdudas** [comment]
@justjais rebased

**Pull request merged**
