### PR TITLE
To fix ios_command command prompt example doc

### PR DESCRIPTION
**Pull request by justjais**
##### SUMMARY

To fix ios_command command prompt example doc, fixes below:
```
- name: run commands that require answering a prompt
  cisco.ios.ios_command:
    commands:
    - command: clear counters GigabitEthernet0/1
      prompt: Clear "show interface" counters on this interface [confirm]
      answer: y
    - command: clear counters GigabitEthernet0/2
      prompt: '[confirm]'
      answer: '
```

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ios_command

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by Andersson007** [comment]
I see escaping issues.
@justjais can't it be escaped with {% raw %} ... {% endraw %} tags or with something else? https://docs.ansible.com/ansible/latest/user_guide/playbooks_advanced_syntax.html#unsafe-or-raw-strings

**Comment by KB-perByte** [comment]
recheck

**Review by KB-perByte — APPROVED** [review]

**Pull request merged**
