### PR TITLE
[ios_interfaces] add mode to ios_interfaces

### PR DESCRIPTION
**Pull request by KB-perByte**
##### SUMMARY

add mode to attribute to ios_interfaces

-  Manage Layer2 or Layer3 state of the interface.
-  For a Layer 2 appliance mode Layer2 adds switchport command ( default impacts idempotency).
-  For a Layer 2 appliance mode Layer3 adds no switchport command.
-  For a Layer 3 appliance mode Layer3/2 has no impact rather produces command fails.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ios_interfaces

##### ADDITIONAL INFORMATION

```paste below
PLAYBOOK 
-------------------------------------------------------------------------------
  tasks:
  - name: Merge provided configuration with device configuration check mode
    cisco.ios.ios_interfaces:
      config:
      - name: GigabitEthernet2
        description: Configured and Merged by Ansible Network
        enabled: true
        mode: layer2
      - name: GigabitEthernet3
        description: Configured and Merged by Ansible Network
        mode: layer3
      state: merged
    check_mode: true

  - name: Merge provided configuration with device configuration
    cisco.ios.ios_interfaces:
      config:
      - name: GigabitEthernet2
        description: Configured and Merged by Ansible Network
        enabled: true
        mode: layer2
      - name: GigabitEthernet3
        description: Configured and Merged by Ansible Network
        mode: layer3
      state: merged
```

```paste below
OUTPUT 
-------------------------------------------------------------------------------
ansible-playbook [core 2.14.1]

TASK [Merge provided configuration with device configuration check mode] *******
changed: [abcd] => changed=true 
  after:
  - enabled: true
    name: GigabitEthernet1
  - description: Configured and Merged by Ansible Network
    enabled: true
    name: GigabitEthernet2
    speed: '1000'
  - enabled: true
    name: GigabitEthernet3
    speed: '1000'
  - enabled: false
    name: GigabitEthernet4
  - enabled: true
    name: Loopback888
  - enabled: true
    name: Loopback999
  before:
  - enabled: true
    name: GigabitEthernet1
  - description: Configured and Merged by Ansible Network
    enabled: true
    name: GigabitEthernet2
    speed: '1000'
  - enabled: true
    name: GigabitEthernet3
    speed: '1000'
  - enabled: false
    name: GigabitEthernet4
  - enabled: true
    name: Loopback888
  - enabled: true
    name: Loopback999
  commands:
  - interface GigabitEthernet2
  - switchport
  - interface GigabitEthernet3
  - description Configured and Merged by Ansible Network
  - no switchport
  invocation:
    module_args:
      config:
      - description: Configured and Merged by Ansible Network
        duplex: null
        enabled: true
        mode: layer2
        mtu: null
        name: GigabitEthernet2
        speed: null
      - description: Configured and Merged by Ansible Network
        duplex: null
        enabled: true
        mode: layer3
        mtu: null
        name: GigabitEthernet3
        speed: null
      running_config: null
      state: merged

TASK [Merge provided configuration with device configuration] ******************
fatal: [abcd]: FAILED! => changed=false 
  module_stderr: |-
    switchport
    switchport
     ^
    % Invalid input detected at '^' marker.
  
    Router(config-if)#
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
```

### CODE REVIEW

**Comment by KB-perByte** [comment]
CC @bentole any feedback on the implementation would be great.
Regards

**Comment by bentole** [comment]
> CC @bentole any feedback on the implementation would be great.
> Regards

HI @KB-perByte ! 

It looks good to me! To play the role of the devil's advocate 😈 I guess you could improve the facts a bit by inferring that if the interface contains the `ip address` command, it's layer 3. If not it's layer2. I believe the `ip address` command is present on all L3 interfaces consistently across all platforms.

**Comment by KB-perByte** [comment]
Hey @bentole, That is the perfect comment, So, there are a couple of ways to figure out if a device is layer2 or layer3 but with our present modules we never validate that, instead we expect the user to be aware of the appliance before they run a playbook against it. Validations and fail on validations are there only if a person can make a blunder with a functionality.
But here the `mode` attribute makes sense only if the switch is a _hybrid_ that supports layer 2 and layer 3 modes. And if it is a simple router `switchport` or `no switchport` is just an invalid command. Adding a validation adds some latency and I was not really convinced about adding it.
If you feel differently about it, let me know.
Regards

**Review by roverflow — APPROVED** [review]
Amazing work!!

**Review by NilashishC — APPROVED** [review]

**Pull request merged**
