### PR TITLE
Add support for autoconfig and dhcp keywords for IPv6 addresses in l3_interfaces

### PR DESCRIPTION
**Pull request by serverwentdown**
##### SUMMARY
Add support for autoconfig and dhcp keywords for IPv6 addresses in l3_interfaces.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
l3_interfaces

##### ADDITIONAL INFORMATION
Tested with IOS 15.2(2a)E1. Resubmit of #15

### CODE REVIEW

**Comment by serverwentdown** [comment]
Anyone I should ping?

**Comment by serverwentdown** [comment]
`validate-modules` in `network-ee-sanity-tests` is failing in files I did not touch...

**Comment by Andersson007** [comment]
there's an integration test failing:
```
2021-03-21 15:00:26.601374 | ubuntu-bionic | TASK [ios_l3_interfaces : Render the commands for provided  configuration] *****
2021-03-21 15:00:26.601604 | ubuntu-bionic | task path: /home/zuul/.ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_l3_interfaces/tests/cli/rendered.yaml:8
2021-03-21 15:00:26.656493 | ubuntu-bionic | <38.108.68.27> attempting to start connection
2021-03-21 15:00:26.657217 | ubuntu-bionic | <38.108.68.27> using connection plugin ansible.netcommon.network_cli
2021-03-21 15:00:26.657609 | ubuntu-bionic | Found ansible-connection at path /home/zuul/venv/bin/ansible-connection
2021-03-21 15:00:27.474484 | ubuntu-bionic | <38.108.68.27> found existing local domain socket, using it!
2021-03-21 15:00:27.476114 | ubuntu-bionic | [WARNING]: Persistent connection logging is enabled for 38.108.68.27. This will
2021-03-21 15:00:27.476144 | ubuntu-bionic | log ALL interactions to /home/zuul/ansible-debug.txt and WILL NOT redact
2021-03-21 15:00:27.476159 | ubuntu-bionic | sensitive configuration like passwords. USE WITH CAUTION!
2021-03-21 15:00:27.476400 | ubuntu-bionic | <38.108.68.27> updating play_context for connection
2021-03-21 15:00:27.476595 | ubuntu-bionic | <38.108.68.27>
2021-03-21 15:00:27.476932 | ubuntu-bionic | <38.108.68.27> local domain socket path is /home/zuul/.ansible/pc/64cfe3150b
2021-03-21 15:00:27.482902 | ubuntu-bionic | redirecting (type: action) cisco.ios.ios_l3_interfaces to cisco.ios.ios
2021-03-21 15:00:27.483710 | ubuntu-bionic | redirecting (type: action) cisco.ios.ios_l3_interfaces to cisco.ios.ios
2021-03-21 15:00:27.485057 | ubuntu-bionic | <38.108.68.27> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
2021-03-21 15:00:27.485459 | ubuntu-bionic | <38.108.68.27> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
2021-03-21 15:00:27.485661 | ubuntu-bionic | <38.108.68.27> ANSIBLE_NETWORK_IMPORT_MODULES: disabled for when not Python 3
2021-03-21 15:00:27.486789 | ubuntu-bionic | <38.108.68.27> ESTABLISH LOCAL CONNECTION FOR USER: zuul
2021-03-21 15:00:27.487093 | ubuntu-bionic | <38.108.68.27> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z `"&& mkdir "` echo /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/ansible-tmp-1616338827.49-20237-164037195307357 `" && echo ansible-tmp-1616338827.49-20237-164037195307357="` echo /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/ansible-tmp-1616338827.49-20237-164037195307357 `" ) && sleep 0'
2021-03-21 15:00:27.519451 | ubuntu-bionic | Using module file /home/zuul/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_l3_interfaces.py
2021-03-21 15:00:27.522020 | ubuntu-bionic | <38.108.68.27> PUT /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/tmpYn7_XS TO /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/ansible-tmp-1616338827.49-20237-164037195307357/AnsiballZ_ios_l3_interfaces.py
2021-03-21 15:00:27.524078 | ubuntu-bionic | <38.108.68.27> EXEC /bin/sh -c 'chmod u+x /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/ansible-tmp-1616338827.49-20237-164037195307357/ /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/ansible-tmp-1616338827.49-20237-164037195307357/AnsiballZ_ios_l3_interfaces.py && sleep 0'
2021-03-21 15:00:27.535415 | ubuntu-bionic | <38.108.68.27> EXEC /bin/sh -c '/home/zuul/venv/bin/python /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/ansible-tmp-1616338827.49-20237-164037195307357/AnsiballZ_ios_l3_interfaces.py && sleep 0'
2021-03-21 15:00:28.162010 | ubuntu-bionic | <38.108.68.27> EXEC /bin/sh -c 'rm -f -r /home/zuul/.ansible/tmp/ansible-local-19262uAFI0Z/ansible-tmp-1616338827.49-20237-164037195307357/ > /dev/null 2>&1 && sleep 0'
2021-03-21 15:00:28.186166 | ubuntu-bionic | ok: [ios-15.6-2T] => {
2021-03-21 15:00:28.186221 | ubuntu-bionic |     "changed": false,
2021-03-21 15:00:28.186236 | ubuntu-bionic |     "invocation": {
2021-03-21 15:00:28.186249 | ubuntu-bionic |         "module_args": {
2021-03-21 15:00:28.186261 | ubuntu-bionic |             "config": [
2021-03-21 15:00:28.186273 | ubuntu-bionic |                 {
2021-03-21 15:00:28.186284 | ubuntu-bionic |                     "ipv4": [
2021-03-21 15:00:28.186296 | ubuntu-bionic |                         {
2021-03-21 15:00:28.186313 | ubuntu-bionic |                             "address": "192.0.2.1 255.255.255.0",
2021-03-21 15:00:28.186328 | ubuntu-bionic |                             "dhcp_client": null,
2021-03-21 15:00:28.186370 | ubuntu-bionic |                             "dhcp_hostname": null,
2021-03-21 15:00:28.186400 | ubuntu-bionic |                             "secondary": null
2021-03-21 15:00:28.186416 | ubuntu-bionic |                         }
2021-03-21 15:00:28.186428 | ubuntu-bionic |                     ],
2021-03-21 15:00:28.186450 | ubuntu-bionic |                     "ipv6": null,
2021-03-21 15:00:28.186481 | ubuntu-bionic |                     "name": "loopback999"
2021-03-21 15:00:28.186495 | ubuntu-bionic |                 },
2021-03-21 15:00:28.186508 | ubuntu-bionic |                 {
2021-03-21 15:00:28.186521 | ubuntu-bionic |                     "ipv4": [
2021-03-21 15:00:28.186534 | ubuntu-bionic |                         {
2021-03-21 15:00:28.186546 | ubuntu-bionic |                             "address": "dhcp",
2021-03-21 15:00:28.186559 | ubuntu-bionic |                             "dhcp_client": 0,
2021-03-21 15:00:28.186572 | ubuntu-bionic |                             "dhcp_hostname": "test.com",
2021-03-21 15:00:28.186584 | ubuntu-bionic |                             "secondary": null
2021-03-21 15:00:28.186597 | ubuntu-bionic |                         }
2021-03-21 15:00:28.186610 | ubuntu-bionic |                     ],
2021-03-21 15:00:28.186623 | ubuntu-bionic |                     "ipv6": null,
2021-03-21 15:00:28.186635 | ubuntu-bionic |                     "name": "GigabitEthernet0/1"
2021-03-21 15:00:28.186648 | ubuntu-bionic |                 },
2021-03-21 15:00:28.186675 | ubuntu-bionic |                 {
2021-03-21 15:00:28.186688 | ubuntu-bionic |                     "ipv4": [
2021-03-21 15:00:28.186700 | ubuntu-bionic |                         {
2021-03-21 15:00:28.186712 | ubuntu-bionic |                             "address": "198.51.100.1 255.255.255.0",
2021-03-21 15:00:28.186725 | ubuntu-bionic |                             "dhcp_client": null,
2021-03-21 15:00:28.186737 | ubuntu-bionic |                             "dhcp_hostname": null,
2021-03-21 15:00:28.186773 | ubuntu-bionic |                             "secondary": true
2021-03-21 15:00:28.186803 | ubuntu-bionic |                         },
2021-03-21 15:00:28.186815 | ubuntu-bionic |                         {
2021-03-21 15:00:28.186827 | ubuntu-bionic |                             "address": "198.51.100.2 255.255.255.0",
2021-03-21 15:00:28.186838 | ubuntu-bionic |                             "dhcp_client": null,
2021-03-21 15:00:28.186849 | ubuntu-bionic |                             "dhcp_hostname": null,
2021-03-21 15:00:28.186861 | ubuntu-bionic |                             "secondary": null
2021-03-21 15:00:28.186886 | ubuntu-bionic |                         }
2021-03-21 15:00:28.186917 | ubuntu-bionic |                     ],
2021-03-21 15:00:28.186932 | ubuntu-bionic |                     "ipv6": [
2021-03-21 15:00:28.186951 | ubuntu-bionic |                         {
2021-03-21 15:00:28.186963 | ubuntu-bionic |                             "address": "2001:db8:0:3::/64"
2021-03-21 15:00:28.186987 | ubuntu-bionic |                         }
2021-03-21 15:00:28.187002 | ubuntu-bionic |                     ],
2021-03-21 15:00:28.187014 | ubuntu-bionic |                     "name": "GigabitEthernet0/2"
2021-03-21 15:00:28.187026 | ubuntu-bionic |                 }
2021-03-21 15:00:28.187038 | ubuntu-bionic |             ],
2021-03-21 15:00:28.187050 | ubuntu-bionic |             "running_config": null,
2021-03-21 15:00:28.187063 | ubuntu-bionic |             "state": "rendered"
2021-03-21 15:00:28.187075 | ubuntu-bionic |         }
2021-03-21 15:00:28.187087 | ubuntu-bionic |     },
2021-03-21 15:00:28.187098 | ubuntu-bionic |     "rendered": [
2021-03-21 15:00:28.187110 | ubuntu-bionic |         "interface loopback999",
2021-03-21 15:00:28.187122 | ubuntu-bionic |         "ip address 192.0.2.1 255.255.255.0",
2021-03-21 15:00:28.187133 | ubuntu-bionic |         "interface GigabitEthernet0/1",
2021-03-21 15:00:28.187146 | ubuntu-bionic |         "ip address dhcp client-id GigabitEthernet0/0 hostname test.com",
2021-03-21 15:00:28.187169 | ubuntu-bionic |         "interface GigabitEthernet0/2",
2021-03-21 15:00:28.187203 | ubuntu-bionic |         "ip address 198.51.100.1 255.255.255.0 secondary",
2021-03-21 15:00:28.187217 | ubuntu-bionic |         "ip address 198.51.100.2 255.255.255.0",
2021-03-21 15:00:28.187229 | ubuntu-bionic |         "ipv6 address 2001:db8:0:3::/64"
2021-03-21 15:00:28.187241 | ubuntu-bionic |     ]
2021-03-21 15:00:28.187252 | ubuntu-bionic | }
2021-03-21 15:00:28.201272 | ubuntu-bionic |
2021-03-21 15:00:28.201303 | ubuntu-bionic | TASK [ios_l3_interfaces : assert] **********************************************
2021-03-21 15:00:28.201620 | ubuntu-bionic | task path: /home/zuul/.ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_l3_interfaces/tests/cli/rendered.yaml:30
2021-03-21 15:00:28.276164 | ubuntu-bionic | <38.108.68.27> attempting to start connection
2021-03-21 15:00:28.276776 | ubuntu-bionic | <38.108.68.27> using connection plugin ansible.netcommon.network_cli
2021-03-21 15:00:28.277347 | ubuntu-bionic | Found ansible-connection at path /home/zuul/venv/bin/ansible-connection
2021-03-21 15:00:29.249599 | ubuntu-bionic | <38.108.68.27> found existing local domain socket, using it!
2021-03-21 15:00:29.252708 | ubuntu-bionic | [WARNING]: Persistent connection logging is enabled for 38.108.68.27. This will
2021-03-21 15:00:29.252749 | ubuntu-bionic | log ALL interactions to /home/zuul/ansible-debug.txt and WILL NOT redact
2021-03-21 15:00:29.252792 | ubuntu-bionic | sensitive configuration like passwords. USE WITH CAUTION!
2021-03-21 15:00:29.253107 | ubuntu-bionic | <38.108.68.27> updating play_context for connection
2021-03-21 15:00:29.253297 | ubuntu-bionic | <38.108.68.27>
2021-03-21 15:00:29.253869 | ubuntu-bionic | <38.108.68.27> local domain socket path is /home/zuul/.ansible/pc/64cfe3150b
2021-03-21 15:00:29.298815 | ubuntu-bionic | fatal: [ios-15.6-2T]: FAILED! => {
2021-03-21 15:00:29.298928 | ubuntu-bionic |     "assertion": "result.rendered|symmetric_difference(merged.commands) == []",
2021-03-21 15:00:29.298956 | ubuntu-bionic |     "changed": false,
2021-03-21 15:00:29.298981 | ubuntu-bionic |     "evaluated_to": false,
2021-03-21 15:00:29.299011 | ubuntu-bionic |     "msg": "Assertion failed"
2021-03-21 15:00:29.299029 | ubuntu-bionic | }
2021-03-21 15:00:29.375297 | ubuntu-bionic |
2021-03-21 15:00:29.375388 | ubuntu-bionic | PLAY RECAP *********************************************************************
2021-03-21 15:00:29.375904 | ubuntu-bionic | ios-15.6-2T                : ok=84   changed=19   unreachable=0    failed=1    skipped=0    rescued=0    ignored=5
```
Is it related?
You can find the full log [here](https://5e3693cc1789f573d09c-82f934c99664ecb89110398588129d53.ssl.cf1.rackcdn.com/269/ae5040ccab7660bfe570c339d1267ab8435a7c45/check/ansible-test-network-integration-ios-network_cli-python27-stable210/1c7a797/job-output.html)

**Comment by Andersson007** [comment]
recheck

**Comment by serverwentdown** [comment]
@Andersson007 I finally understood how the tests work, :+1:

**Comment by serverwentdown** [comment]
An interesting behaviour I just discovered is `ipv6 address` gets sorted by IOS, so 
```
ipv6 address autoconfig
ipv6 address fc00::1/64
ipv6 address dhcp
``` 
Gets sorted into
```
ipv6 address dhcp
ipv6 address fc00::1/64
ipv6 address autoconfig
``` 

And doing `no ipv6 address` removes autoconfig and static addresses, but not dhcp. Might need to amend the test for that.

**Comment by serverwentdown** [comment]
I can't figure out why the ee-sanity-tests are failing: https://dashboard.zuul.ansible.com/t/ansible/build/100cfda888c344ef87cab9a54d4aae5a/log/job-output.txt#676

**Comment by Andersson007** [comment]
@serverwentdown the failings are not related to this PR, I created an issue https://github.com/ansible-collections/cisco.ios/issues/300. I can't fix it myself, unfortunately. So we should wait until someone from the maintainers fix them

**Comment by justjais** [comment]
recheck

**Review by justjais — APPROVED** [review]

**Comment by Andersson007** [comment]
@serverwentdown thank you for the contribution! @justjais thanks for reviewing and gating!:)

**Pull request merged**
