### PR TITLE
Proposed feature for Virtual Switch System Detection

### PR DESCRIPTION
**Pull request by tweippert**
##### SUMMARY
Proposed detection of Virtual Switch Systems / Stacks. Fixes Feature idea #46

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ios_facts

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
@tweippert can you plz fix the test failures and update the PR.

**Comment by tweippert** [comment]
@justjais Will look on it, if i understand it correclty mainly the "show virtual switch" output file is missing for the test unit to work properly ... Had currently no acces to a VSS enabled switch, hopefully next week, will update PR accordingly.

**Comment by tweippert** [comment]
I think i fixed the errors i introduced, the others maybe someone can give me a hint where to look, or if they are introduced with my changes!?

**Comment by justjais** [comment]
@tweippert yes, test failures are due to the PR changes. Plz check: https://1d32c92eac4827c7a210-f4b942705cdf5f84b1256c174dbe9f30.ssl.cf2.rackcdn.com/51/5ef2b8eda5a88a50f7881b7bc08e180cebf9c854/check/ansible-test-network-integration-ios-network_cli-python27-stable29/dd747b2/controller/ara-report/reports/066b81fe-1491-45f9-90b2-8f527f947da6.html 
And to check the debug logs to get to the exact failure u can browse to the debug log via: `ansible/check_details->zuul_failure_log_url->controller->
ansible-debug.txt`

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by tweippert** [comment]
Found the error. Fixed.

**Review by justjais — APPROVED** [review]

**Comment by pabelanger** [comment]
This will need a changelog fragment now, all PRs should include that moving forward.

**Comment by tweippert** [comment]
> This will need a changelog fragment now, all PRs should include that moving forward.

Added changelog fragment

**Comment by tweippert** [comment]
Is there an update on the topic?

**Comment by justjais** [comment]
@tweippert I've applied the gate, if everything works as expected it should get merged and queued for IOS Jan release.

**Pull request merged**
