### PR TITLE
Remove tests/sanity/requirements.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/overview/issues/43

### CODE REVIEW

**Comment by Andersson007** [comment]
@NilashishC could you please take a look?

**Review by felixfontein — APPROVED** [review]

**Comment by Andersson007** [comment]
@felixfontein thanks for reviewing!

**Comment by Andersson007** [comment]
recheck

**Comment by Andersson007** [comment]
hm, everything was green yesterday

**Comment by Andersson007** [comment]
recheck

**Pull request merged**
