### PR TITLE
IOS resource modules minor doc updates

### PR DESCRIPTION
**Pull request by justjais**
##### SUMMARY

IOS resource modules minor doc updates

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ios_bgp_global
ios_acls
ios_ospfv2
ios_static_routes

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by rohitthakur2590 — APPROVED** [review]

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Pull request merged**
