### PR TITLE
To fix IOS l2 interfaces for traceback error and merge operation not working as expected

### PR DESCRIPTION
**Pull request by justjais**
##### SUMMARY

To fix IOS l2 interfaces for traceback error and merge operation not working as expected raised in bug #44 and #77 .

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_l2_interfaces

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
Test failed due to env issue `"msg": "[Errno None] Unable to connect to port 22 on 74.63.204.61"`

**Comment by justjais** [comment]
recheck

**Review by NilashishC — APPROVED** [review]

**Comment by NilashishC** [comment]
+1, needs a changelog.

**Comment by Colotpat** [comment]
Hello, i have the same problem.  i'm running python  3.8.10 with ansible 2.9.6.
Playbook
  - name: grab info
    ios_facts:
      gather_subset: all
      gather_network_resources: all

applied to a stack of C9200L-48P-4G running 17.3.4 CAT9K_LITE_IOSXE => OK
applied to switch C9500-24Y4C running 17.3.4 network-advantage => NOT OK
applied to Core C8300-1N1S-4T2X running 17.3.4a => NOT OK

When not OK, i have the following error:

fatal: [XXXXXXXXt]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "value of encapsulation must be one of: dot1q, isl, negotiate, got: dot1Q 1164 found in config -> trunk"}


For me, it's coming from the fact that ansible is expecting that we must define the encapsulation method, which is no more the case on IOS-XE

**Pull request merged**
