### PR TITLE
bindep.txt: add libssh-devel

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1228

### CODE REVIEW

**Comment by KB-perByte** [comment]
recheck

**Comment by KB-perByte** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
The test fails because of this:
```
ERROR: Found 6 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/ios_command.py:0:0: invalid-documentation-markup: DOCUMENTATION.description: Directive "M(ios_config)" must contain a FQCN for dictionary value @ data['description']. Got ['Sends arbitrary commands to an ios node and returns the results read from the device. This module includes an argument that will cause the module to wait for a specific condition before returning or timing out if the condition is not met.', 'This module does not support running commands in configuration mode. Please use M(ios_config) to configure IOS devices.']
ERROR: plugins/modules/ios_facts.py:0:0: invalid-documentation-markup: DOCUMENTATION.options.gather_network_resources.description: Directive "M(!)" must contain a FQCN for dictionary value @ data['options']['gather_network_resources']['description']. Got ["When supplied, this argument will restrict the facts collected to a given subset. Possible values for this argument include all and the resources like interfaces, vlans etc. Can specify a list of values to include a larger subset. Values can also be used with an initial C(M(!)) to specify that a specific subset should not be collected. Valid subsets are 'all', 'interfaces', 'l2_interfaces', 'vlans', 'lag_interfaces', 'lacp', 'lacp_interfaces', 'lldp_global', 'lldp_interfaces', 'l3_interface...
ERROR: plugins/modules/ios_ping.py:0:0: invalid-documentation-markup: DOCUMENTATION.description: Directive "M(net_ping)" must contain a FQCN for dictionary value @ data['description']. Got ['Tests reachability using ping from switch to a remote destination.', 'For a general purpose network module, see the M(net_ping) module.', 'For Windows targets, use the M(win_ping) module instead.', 'For targets running Python, use the M(ping) module instead.']
ERROR: plugins/modules/ios_ping.py:0:0: invalid-documentation-markup: DOCUMENTATION.notes.0: Directive "M(net_ping)" must contain a FQCN @ data['notes'][0]. Got 'For a general purpose network module, see the M(net_ping) module.'
ERROR: plugins/modules/ios_ping.py:0:0: invalid-documentation-markup: DOCUMENTATION.notes.1: Directive "M(win_ping)" must contain a FQCN @ data['notes'][1]. Got 'For Windows targets, use the M(win_ping) module instead.'
ERROR: plugins/modules/ios_ping.py:0:0: invalid-documentation-markup: DOCUMENTATION.notes.2: Directive "M(ping)" must contain a FQCN @ data['notes'][2]. Got 'For targets running Python, use the M(ping) module instead.'
```

**Pull request closed without merging**
