### PR TITLE
Bugfixes for ios_acls after last commit regarding this module

### LINKED ISSUE #973: Gathered facts for standard acl do not match actual acl and contain unsupported attributes (first octet of ip parsed to protocol_number)
##### SUMMARY
Trying to add/replace/modify a standard ACL fails with
```
Unsupported attribute for standard ACL - protocol_options.
```
when the playbook doesn't include any protocol_options.

I appears the acls module fails to parse the config in the router correctly. Instead of correctly parsing a source address/host and wildcard. A line like
```
ip access-list standard SNMP-SECURITY
  permit 10.255.236.0 0.0.3.255
```
results in gathered facts as
```
                        {
                            "grant": "permit",
                            "protocol_options": {
                                "protocol_number": 10
                            }
                        }
```
where the first octet of the ip address somehow ends up as a protocol_number.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module: cisco.ios.ios_acls

##### ANSIBLE VERSION
```
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/daniel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
cisco.ios         5.2.0  
```

##### CONFIGURATION
```
CONFIG_FILE() = /etc/ansible/ansible.cfg
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
source machine: Debian/12

destination router:
```
C927-4PLTEGB
Cisco IOS Software, C900 Software (C900-UNIVERSALK9-M), Version 15.9(3)M4, RELEASE SOFTWARE (fc3)
```

##### STEPS TO REPRODUCE
playbook:
```
    - name: gather acls
      cisco.ios.ios_acls:
        config:
        state: gathered
      tags: acls,aclsv4

    - name: acls
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
            - name: SNMP-SECURITY
              acl_type: standard
              aces:
                - sequence: 10
                  grant: permit
                  source: 
                    address: 185.1.2.3
                    wildcard_bits: 0.0.0.7
                - sequence: 20
                  grant: permit
                  source:
                    address: 10.255.236.0
                    wildcard_bits: 0.0.3.255
                - sequence: 990
                  grant: deny
                  source:
                    any: true
                  destination:
                    any: true
        state: merged
      tags: acls,aclsv4
```

current ACL in router:
```
ip access-list standard SNMP-SECURITY
 permit 185.1.2.3 0.0.0.7
 permit 10.255.236.0 0.0.3.255
 deny   any
```

##### EXPECTED RESULTS
Since the the desired ACL in playbook and router are the same, nothing should happen.

##### ACTUAL RESULTS
task fails:
```
Unsupported attribute for standard ACL - protocol_options.
```

Output from the fail
```
fatal: [40457]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "acls": [
                        {
                            "aces": [
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "remarks": null,
                                    "sequence": 10,
                                    "source": {
                                        "address": "185.1.2.3",
                                        "any": null,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": "0.0.0.7"
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "remarks": null,
                                    "sequence": 20,
                                    "source": {
                                        "address": "10.255.236.0",
                                        "any": null,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": "0.0.3.255"
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": {
                                        "address": null,
                                        "any": true,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "deny",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "remarks": null,
                                    "sequence": 990,
                                    "source": {
                                        "address": null,
                                        "any": true,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                }
                            ],
                            "acl_type": "standard",
                            "name": "SNMP-SECURITY"
                        }
                    ],
                    "afi": "ipv4"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "Unsupported attribute for standard ACL - protocol_options."
}
```

Relevant output from the gathered:
```
ok: [40457] => {
    "changed": false,
    "gathered": [
        {
            "acls": [
                {
                    "aces": [
                        {
                            "grant": "permit",
                            "protocol_options": {
                                "protocol_number": 185
                            }
                        },
                        {
                            "grant": "permit",
                            "protocol_options": {
                                "protocol_number": 10
                            }
                        },
                        {
                            "grant": "deny"
                        }
                    ],
                    "acl_type": "standard",
                    "name": "SNMP-SECURITY"
                },
            ],
            "afi": "ipv4"
        }
    ],
    "invocation": {
        "module_args": {
            "config": null,
            "running_config": null,
            "state": "gathered"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by earendilfr**
##### SUMMARY
After the commit 43658026568ea4d97b54b696ba99125dc680a64b, the way to restrieve the ACLs has changed and so, the regexp used to match the standard ACE doesn't working anymore:

on IOS-XE, the standard ACL output could be with or without the sequence number:

exemple1:
ip access-list standard acl-mgmt-networks
 10 permit 10.0.0.0 0.0.1.255
 20 permit 172.16.0.0 0.0.1.255
 30 permit 192.168.0.0 0.0.7.255

exemple2:
ip access-list standard acl-mgmt-networks
 permit 10.132.64.0 0.0.1.255
 permit 10.208.232.0 0.0.1.255
 permit 172.31.24.0 0.0.7.255

Fix #973 

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by KB-perByte** [comment]
@earendilfr Which appliance version are you testing the changes against?

**Comment by earendilfr** [comment]
Concerning the regexp used to check IPv4 and IPv6, I have used this gist code:
https://gist.github.com/dfee/6ed3a4b05cfe7a6faf40a2102408d5d8

**Comment by KB-perByte** [comment]
@earendilfr I meant which iosxe version are you testing the PR with?

**Comment by earendilfr** [comment]
> @earendilfr I meant which iosxe version are you testing the PR with?

I have tested on:
- IOS-XE: 16.12.6 & 03.07.05E
- IOS: 15.2(4)E10 & 15.0(2)SE10a

**Comment by KB-perByte** [comment]
@earendilfr Please note that we don't support any of the EOL'd versions of cisco ios or ios xe.
A path has been added to the cisco.ios v5.3.0 you are advised to check it, for the fix.
Regards.

**Comment by earendilfr** [comment]
> @earendilfr Please note that we don't support any of the EOL'd versions of cisco ios or ios xe. A path has been added to the cisco.ios v5.3.0 you are advised to check it, for the fix. Regards.

I have a strange behavior: when I push currently, the module doesn't parse correctly the ACL so, it delete the current line and push exactly the same:
```
TASK [acls : Configure standard ACLs] ******************************************************************************************************************************************************************************************************task path: /opt/ansible/roles/acls/tasks/ios-xe.yml:2
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
changed: [sph-dou-csw02] => {
    "after": [
        {
            "acls": [
                {                                                                                                                                                                                                                                               "acl_type": "extended",
                    "name": "CISCO-CWA-URL-REDIRECT-ACL"
                },
                {
                    "aces": [
                        {
                            "grant": "permit",
                            "source": {
                                "address": "10.132.64.0",
                                "wildcard_bits": "0.0.1.255"
                            }
                        },
                        {
                            "grant": "permit",
                            "source": {
                                "address": "10.208.232.0",
                                "wildcard_bits": "0.0.1.255"
                            }
                        },
                        {
                            "grant": "permit",
                            "source": {
                                "address": "172.31.24.0",
                                "wildcard_bits": "0.0.7.255"
                            }
                        }
                    ],
                    "acl_type": "standard",
                    "name": "acl-mgmt-networks"
                },
                {
                    "acl_type": "extended",
                    "name": "preauth_ipv4_acl (per-user)"
                },
                {
                    "acl_type": "extended",
                    "name": "sl_def_acl"
                }
            ],
            "afi": "ipv4"
        },
        {
            "acls": [
                {
                    "name": "preauth_ipv6_acl (per-user)"
                }
            ],
            "afi": "ipv6"
        }
    ],
    "before": [
        {
            "acls": [
                {
                    "acl_type": "extended",
                    "name": "CISCO-CWA-URL-REDIRECT-ACL"
                },
                {
                    "aces": [
                        {
                            "grant": "permit",
                            "source": {
                                "address": "10.132.64.0",
                                "wildcard_bits": "0.0.1.255"
                            }
                        },
                        {
                            "grant": "permit",
                            "source": {
                                "address": "10.208.232.0",
                                "wildcard_bits": "0.0.1.255"
                            }
                        },
                        {
                            "grant": "permit",
                            "source": {
                                "address": "172.31.24.0",
                                "wildcard_bits": "0.0.7.255"
                            }
                        }
                    ],
                    "acl_type": "standard",
                    "name": "acl-mgmt-networks"
                },
                {
                    "acl_type": "extended",
                    "name": "preauth_ipv4_acl (per-user)"
                },
                {
                    "acl_type": "extended",
                    "name": "sl_def_acl"
                }
            ],
            "afi": "ipv4"
        },
        {
            "acls": [
                {
                    "name": "preauth_ipv6_acl (per-user)"
                }
            ],
            "afi": "ipv6"
        }
    ],
    "changed": true,
    "commands": [
        "ip access-list standard acl-mgmt-networks",
        "no permit 10.132.64.0 0.0.1.255",
        "no permit 10.208.232.0 0.0.1.255",
        "no permit 172.31.24.0 0.0.7.255",
        "permit 10.132.64.0 0.0.1.255",
        "permit 10.208.232.0 0.0.1.255",
        "permit 172.31.24.0 0.0.7.255"
    ],
    "invocation": {                                                                                                                                                                                                                                 "module_args": {
            "config": [
                {
                    "acls": [
                        {
                            "aces": [
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": "10.132.64.0",
                                        "any": null,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": "0.0.1.255"
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": "10.208.232.0",
                                        "any": null,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": "0.0.1.255"
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": "172.31.24.0",
                                        "any": null,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": "0.0.7.255"
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                }
                            ],
                            "acl_type": "standard",
                            "name": "acl-mgmt-networks"
                        }
                    ],
                    "afi": "ipv4"
                }
            ],
            "running_config": null,
            "state": "replaced"
        }
    }
}
```

I will try to understand why...

**Comment by earendilfr** [comment]
I have found something strange: when the sequence is not present, it's doesn't add correctly the fake sequence number for the ACE.
You can fix it easilly like that (in file [plugins/module_utils/network/ios/config/acls/acls.p](https://github.com/ansible-collections/cisco.ios/blob/main/plugins/module_utils/network/ios/config/acls/acls.py)) ; line 269

```python
        temp = dict() 
        if param:
            for each in param:  # ipv4 and ipv6 acl
                temp_acls = {}
                if each.get("acls"):
                    for acl in each.get("acls"):  # check each acl for aces
                        temp_aces = {}
                        if acl.get("aces"):
                            rem_idx = 0  # remarks if defined in an ace
                            for count, ace in enumerate(acl.get("aces")):  # each ace turned to dict
                                if (
                                    ace.get("destination")
                                    and ace.get("destination", {}).get(
                                        "port_protocol",
                                        {},
                                    )
                                    and not ace.get("destination", {})
                                    .get("port_protocol", {})
                                    .get("range")
```

- Remove initial count variable
- loop on ACES with `enumerate` to have a count value correct with current ACES list

**Pull request closed without merging**
