### PR TITLE
To fix Cisco IOS sanity tests

### PR DESCRIPTION
**Pull request by justjais**
Depends-On: https://github.com/ansible-collections/cisco.ios/pull/82
##### SUMMARY

To fix Cisco IOS sanity tests

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_*

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
