### PR TITLE
[ios_interfaces] fix after state

### PR DESCRIPTION
**Pull request by akira6592**
##### SUMMARY

fix after state example  with `state: replaced` and `state: overridden`.

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
@akira6592 I see the changelog updated for `ios_acls` doc changes, but the relevant merge for `ios_acls` module doc file is not updated, can you plz update the same for the PR to get merged.

**Comment by akira6592** [comment]
@justjais Sorry for the confusion.. 
I updated this PR by  `ios_acls` doc changes.

Should I colse #329 ?

**Comment by justjais** [comment]
@akira6592 perfect n thanks for your contribution.

**Review by justjais — APPROVED** [review]

**Pull request merged**
