### PR TITLE
fix description for direction of wildcard_bits and port_protocol

### PR DESCRIPTION
**Pull request by akira6592**
##### SUMMARY

fix description for direction of `wildcard_bits` and `port_protocol`.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- `ios_acls`

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
@akira6592 can you include the changelog for the PR, also as #330 is also docs PR can u plz merge both these PRs and have a single changelog for both and close the other PR

**Comment by akira6592** [comment]
@justjais Thank you for information. I added merged changelog to #330

**Comment by akira6592** [comment]
I made the same fix in #330  so I close this PR.

**Pull request closed without merging**
