### PR TITLE
Add support for single_user_mode

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
Depends-On: https://github.com/ansible-collections/cisco.ios/pull/251

##### SUMMARY
- Targets https://github.com/ansible-collections/ansible.netcommon/issues/73
- Add support for configuration caching (`single_user_mode`).
- This patch ensures that we reuse device_info dictionary and not fetch it from the device
   every time get_device_info() is called.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
cliconf/ios.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by trishnaguha** [comment]
@justjais Please review the PR.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by justjais — APPROVED** [review]

**Pull request merged**
