### PR TITLE
BGP AF Parsing Optimization

### PR DESCRIPTION
**Pull request by bentole**
##### SUMMARY
This is a supplement to PR #687 by optimizing parsing of existing Jinja2 templates.

It improves the time it takes to deploy playbooks to routers with massive BGP configurations as discussed in #682 avoiding `socket path /home/bol/.ansible/pc/9857e85642 does not exist or cannot be found`

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
cisco.ios.ios_address_family

##### ADDITIONAL INFORMATION

To verify the effects of this PR, use the playbook and the configuration mentioned: [here](https://github.com/ansible-collections/cisco.ios/issues/682#issuecomment-1300634545).

I have also created a test case for this issue [here](https://github.com/bentole/scratch_cisco.ios.ios_bgp_address_family) which demonstrates the differences between the optimized vs. original parsers.

### CODE REVIEW

**Comment by KB-perByte** [comment]
Hey @bentole looking at your fix it would make it overly complicated on basis of the parsing that is being done. 
please check this PR https://github.com/ansible-collections/cisco.ios/pull/687
you may pull the PR and try out a parsed state playbook that just crunches the facts for you.
I am working on the config side code. Please expect the PR to be ready in a day or two.
Regards

**Comment by bentole** [comment]
> Hey @bentole looking at your fix it would make it overly complicated on basis of the parsing that is being done.
> please check this PR #687
> you may pull the PR and try out a parsed state playbook that just crunches the facts for you.
> I am working on the config side code. Please expect the PR to be ready in a day or two.
> Regards

Sounds good!  I missed your comment so wrote you a reply [here](https://github.com/ansible-collections/cisco.ios/issues/682#issuecomment-1313539972) 😃

**Comment by bentole** [comment]
> Hey @bentole looking at your fix it would make it overly complicated on basis of the parsing that is being done.

Forgot to comment this :) It appears compliated since I'm overrding functions from NetworkTemplate and that requires  a copy of the complete method, but the only lines really added are:

```
lookup_keys = capdict.keys()

for idx, entry in enumerate(tval):
  tval.pop(idx)
  _entry = deepcopy(entry)
  for k, v in _entry.items():
      if k not in data.keys() and k in lookup_keys:
          entry.pop(k)
  tval.append(entry)
```
But again a solution that does not involve overrding functions is definately preferable.

**Comment by bentole** [comment]
The issue that this PR addressed is covered by and fixed more extensively in PR #687

**Pull request closed without merging**
